server:
  port : 8082

eureka:
  client:
    fetchRegistry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        -   id: student-service
            uri: lb://student-service
            predicates:
              - Path=/
        -   id:  information-service
            uri: lb:// information-service
            predicates:
              - Path=/
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include= *:
