server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: server
